apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-hello-world
  name: flask-hello-world
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
        - image: flask-hello-world
          name: flask-hello-world
          ports:
            - containerPort: 8080