apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-hello-world
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: flask-hello-world
              servicePort: 8080