apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-hello-world
  name: flask-hello-world
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: flask-hello-world